### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by RiderCrazy** [aalmazanarbs/hassio_aldes#1]
Hello,

Thanks for this integration.
Unfortunately, it doesn't work for me.

The logs says
Config entry 'Aldes - **@**.**' for aldes integration not ready yet: list index out of range; Retrying in background

I've got only one Aldes product which is a T.One AquaAIR.

Any tips ?

**Comment by aalmazanarbs** [comment]
Hi @RiderCrazy ,

For the moment this integration only supports InspirAIR Home since I do not know the output of the API for other products. Could you provide the output for this endpoint `/aldesoc/v5/users/me/products` for your product?

Even we can have a meeting to check it :)

Regards.

**Comment by RiderCrazy** [comment]
I removed some informations but here it is.

`[{"slaves":[],"masters":[],"indicators":[{"date":"2022-05-30T11:42:29.265Z","type":"WATER_QUANTITY","value":100},{"date":"2022-05-30T11:42:29.265Z","type":"TEMPERATURE","value":22.81},{"date":"2022-05-31T11:23:22.351Z","type":"CLOUD_CONTROLLED","value":null},{"date":"2022-05-31T11:23:22.405Z","type":"SELF_CONTROLLED","value":false}],"indicator":{"fmist":22.0,"fmast":31.0,"cmast":24.0,"cmist":16.0,"date_debut_vac":null,"date_fin_vac":null,"hors_gel":false,"qte_eau_chaude":100,"tmp_principal":22.81,"current_air_mode":"H","current_water_mode":"M","thermostats":[{"ThermostatId":23562,"Name":"Pièce de vie","Type":null,"Order":0,"IconId":3,"Number":0,"TemperatureSet":24,"CurrentTemperature":22.81},{"ThermostatId":23563,"Name":"Chambre","Type":null,"Order":0,"IconId":2,"Number":1,"TemperatureSet":22,"CurrentTemperature":21.25},{"ThermostatId":23564,"Name":"Chambre Ethan","Type":null,"Order":0,"IconId":1,"Number":2,"TemperatureSet":24,"CurrentTemperature":22.18},{"ThermostatId":23565,"Name":"Chambre amis","Type":null,"Order":0,"IconId":4,"Number":3,"TemperatureSet":24,"CurrentTemperature":20.75},{"ThermostatId":23566,"Name":"Chambre Lucas","Type":null,"Order":0,"IconId":1,"Number":4,"TemperatureSet":24,"CurrentTemperature":21.87}],"settings":{"dateTime":null,"people":2,"currency":0,"antilegio":6,"kwh_creuse":0.12,"kwh_pleine":0.15},"indicatorType":"TONE_Indicator"},"thermostats":null,"week_planning":[{"command":"00C"},{"command":"01C"},{"command":"02C"},{"command":"03C"},{"command":"04C"},{"command":"05B"},{"command":"06B"},{"command":"10C"},{"command":"11C"},{"command":"12C"},{"command":"13C"},{"command":"14C"},{"command":"15C"},{"command":"16C"},{"command":"20C"},{"command":"21C"},{"command":"22C"},{"command":"23C"},{"command":"24C"},{"command":"25C"},{"command":"26C"},{"command":"30C"},{"command":"31C"},{"command":"32C"},{"command":"33C"},{"command":"34C"},{"command":"35C"},{"command":"36C"},{"command":"40C"},{"command":"41C"},{"command":"42C"},{"command":"43C"},{"command":"44C"},{"command":"45C"},{"command":"46C"},{"command":"50C"},{"command":"51C"},{"command":"52C"},{"command":"53C"},{"command":"54C"},{"command":"55C"},{"command":"56C"},{"command":"60C"},{"command":"61C"},{"command":"62C"},{"command":"63C"},{"command":"64C"},{"command":"65C"},{"command":"66C"},{"command":"70B"},{"command":"71B"},{"command":"72B"},{"command":"73B"},{"command":"74B"},{"command":"75C"},{"command":"76C"},{"command":"80C"},{"command":"81C"},{"command":"82C"},{"command":"83C"},{"command":"84C"},{"command":"85B"},{"command":"86B"},{"command":"90C"},{"command":"91C"},{"command":"92C"},{"command":"93C"},{"command":"94C"},{"command":"95B"},{"command":"96B"},{"command":"A0C"},{"command":"A1C"},{"command":"A2C"},{"command":"A3C"},{"command":"A4C"},{"command":"A5B"},{"command":"A6B"},{"command":"B0C"},{"command":"B1C"},{"command":"B2C"},{"command":"B3C"},{"command":"B4C"},{"command":"B5B"},{"command":"B6B"},{"command":"C0C"},{"command":"C1C"},{"command":"C2C"},{"command":"C3C"},{"command":"C4C"},{"command":"C5B"},{"command":"C6B"},{"command":"D0C"},{"command":"D1C"},{"command":"D2C"},{"command":"D3C"},{"command":"D4C"},{"command":"D5B"},{"command":"D6B"},{"command":"E0C"},{"command":"E1C"},{"command":"E2B"},{"command":"E3C"},{"command":"E4C"},{"command":"E5B"},{"command":"E6B"},{"command":"F0C"},{"command":"F1C"},{"command":"F2B"},{"command":"F3C"},{"command":"F4C"},{"command":"F5B"},{"command":"F6B"},{"command":"G0C"},{"command":"G1C"},{"command":"G2B"},{"command":"G3C"},{"command":"G4C"},{"command":"G5B"},{"command":"G6B"},{"command":"H0B"},{"command":"H1B"},{"command":"H2B"},{"command":"H3B"},{"command":"H4B"},{"command":"H5B"},{"command":"H6B"},{"command":"I0B"},{"command":"I1B"},{"command":"I2B"},{"command":"I3B"},{"command":"I4B"},{"command":"I5B"},{"command":"I6B"},{"command":"J0B"},{"command":"J1B"},{"command":"J2B"},{"command":"J3B"},{"command":"J4B"},{"command":"J5B"},{"command":"J6B"},{"command":"K0B"},{"command":"K1B"},{"command":"K2B"},{"command":"K3B"},{"command":"K4B"},{"command":"K5B"},{"command":"K6B"},{"command":"L0B"},{"command":"L1B"},{"command":"L2B"},{"command":"L3B"},{"command":"L4B"},{"command":"L5B"},{"command":"L6B"},{"command":"M0B"},{"command":"M1B"},{"command":"M2B"},{"command":"M3B"},{"command":"M4B"},{"command":"M5B"},{"command":"M6B"},{"command":"N0C"},{"command":"N1C"},{"command":"N2C"},{"command":"N3C"},{"command":"N4B"},{"command":"N5B"},{"command":"N6B"}],"week_planning2":[{"command":"00C"},{"command":"01C"},{"command":"02C"},{"command":"03C"},{"command":"04C"},{"command":"05C"},{"command":"06C"},{"command":"10C"},{"command":"11C"},{"command":"12C"},{"command":"13C"},{"command":"14C"},{"command":"15C"},{"command":"16C"},{"command":"20C"},{"command":"21C"},{"command":"22C"},{"command":"23C"},{"command":"24C"},{"command":"25C"},{"command":"26C"},{"command":"30C"},{"command":"31C"},{"command":"32C"},{"command":"33C"},{"command":"34C"},{"command":"35C"},{"command":"36C"},{"command":"40C"},{"command":"41C"},{"command":"42C"},{"command":"43C"},{"command":"44C"},{"command":"45C"},{"command":"46C"},{"command":"50C"},{"command":"51C"},{"command":"52C"},{"command":"53C"},{"command":"54C"},{"command":"55C"},{"command":"56C"},{"command":"60C"},{"command":"61C"},{"command":"62C"},{"command":"63C"},{"command":"64C"},{"command":"65C"},{"command":"66C"},{"command":"70B"},{"command":"71B"},{"command":"72B"},{"command":"73B"},{"command":"74B"},{"command":"75C"},{"command":"76C"},{"command":"80B"},{"command":"81B"},{"command":"82B"},{"command":"83B"},{"command":"84B"},{"command":"85B"},{"command":"86B"},{"command":"90C"},{"command":"91C"},{"command":"92C"},{"command":"93C"},{"command":"94C"},{"command":"95B"},{"command":"96B"},{"command":"A0C"},{"command":"A1C"},{"command":"A2C"},{"command":"A3C"},{"command":"A4C"},{"command":"A5B"},{"command":"A6B"},{"command":"B0C"},{"command":"B1C"},{"command":"B2C"},{"command":"B3C"},{"command":"B4C"},{"command":"B5B"},{"command":"B6B"},{"command":"C0B"},{"command":"C1B"},{"command":"C2B"},{"command":"C3B"},{"command":"C4B"},{"command":"C5B"},{"command":"C6B"},{"command":"D0B"},{"command":"D1B"},{"command":"D2B"},{"command":"D3B"},{"command":"D4B"},{"command":"D5B"},{"command":"D6B"},{"command":"E0C"},{"command":"E1C"},{"command":"E2C"},{"command":"E3C"},{"command":"E4C"},{"command":"E5B"},{"command":"E6B"},{"command":"F0C"},{"command":"F1C"},{"command":"F2C"},{"command":"F3C"},{"command":"F4C"},{"command":"F5B"},{"command":"F6B"},{"command":"G0C"},{"command":"G1C"},{"command":"G2C"},{"command":"G3C"},{"command":"G4C"},{"command":"G5B"},{"command":"G6B"},{"command":"H0B"},{"command":"H1B"},{"command":"H2B"},{"command":"H3B"},{"command":"H4B"},{"command":"H5B"},{"command":"H6B"},{"command":"I0B"},{"command":"I1B"},{"command":"I2B"},{"command":"I3B"},{"command":"I4B"},{"command":"I5B"},{"command":"I6B"},{"command":"J0B"},{"command":"J1B"},{"command":"J2B"},{"command":"J3B"},{"command":"J4B"},{"command":"J5B"},{"command":"J6B"},{"command":"K0B"},{"command":"K1B"},{"command":"K2B"},{"command":"K3B"},{"command":"K4B"},{"command":"K5B"},{"command":"K6B"},{"command":"L0B"},{"command":"L1B"},{"command":"L2B"},{"command":"L3B"},{"command":"L4B"},{"command":"L5B"},{"command":"L6B"},{"command":"M0C"},{"command":"M1C"},{"command":"M2C"},{"command":"M3C"},{"command":"M4C"},{"command":"M5B"},{"command":"M6B"},{"command":"N0C"},{"command":"N1C"},{"command":"N2C"},{"command":"N3C"},{"command":"N4C"},{"command":"N5C"},{"command":"N6C"}],"week_planning3":[{"command":"00C"},{"command":"01C"},{"command":"02C"},{"command":"03C"},{"command":"04C"},{"command":"05C"},{"command":"06C"},{"command":"10C"},{"command":"11C"},{"command":"12C"},{"command":"13C"},{"command":"14C"},{"command":"15C"},{"command":"16C"},{"command":"20C"},{"command":"21C"},{"command":"22C"},{"command":"23C"},{"command":"24C"},{"command":"25C"},{"command":"26C"},{"command":"30C"},{"command":"31C"},{"command":"32C"},{"command":"33C"},{"command":"34C"},{"command":"35C"},{"command":"36C"},{"command":"40C"},{"command":"41C"},{"command":"42C"},{"command":"43C"},{"command":"44C"},{"command":"45C"},{"command":"46C"},{"command":"50C"},{"command":"51C"},{"command":"52C"},{"command":"53C"},{"command":"54C"},{"command":"55C"},{"command":"56C"},{"command":"60C"},{"command":"61C"},{"command":"62C"},{"command":"63C"},{"command":"64C"},{"command":"65C"},{"command":"66C"},{"command":"70C"},{"command":"71C"},{"command":"72C"},{"command":"73C"},{"command":"74C"},{"command":"75C"},{"command":"76C"},{"command":"80C"},{"command":"81C"},{"command":"82C"},{"command":"83C"},{"command":"84C"},{"command":"85C"},{"command":"86C"},{"command":"90C"},{"command":"91C"},{"command":"92C"},{"command":"93C"},{"command":"94C"},{"command":"95C"},{"command":"96C"},{"command":"A0C"},{"command":"A1C"},{"command":"A2C"},{"command":"A3C"},{"command":"A4C"},{"command":"A5C"},{"command":"A6C"},{"command":"B0C"},{"command":"B1C"},{"command":"B2C"},{"command":"B3C"},{"command":"B4C"},{"command":"B5C"},{"command":"B6C"},{"command":"C0C"},{"command":"C1C"},{"command":"C2C"},{"command":"C3C"},{"command":"C4C"},{"command":"C5B"},{"command":"C6B"},{"command":"D0C"},{"command":"D1C"},{"command":"D2B"},{"command":"D3C"},{"command":"D4C"},{"command":"D5B"},{"command":"D6B"},{"command":"E0C"},{"command":"E1C"},{"command":"E2B"},{"command":"E3C"},{"command":"E4C"},{"command":"E5B"},{"command":"E6B"},{"command":"F0C"},{"command":"F1C"},{"command":"F2B"},{"command":"F3C"},{"command":"F4C"},{"command":"F5B"},{"command":"F6B"},{"command":"G0B"},{"command":"G1B"},{"command":"G2B"},{"command":"G3B"},{"command":"G4B"},{"command":"G5B"},{"command":"G6B"},{"command":"H0B"},{"command":"H1B"},{"command":"H2B"},{"command":"H3B"},{"command":"H4B"},{"command":"H5B"},{"command":"H6B"},{"command":"I0B"},{"command":"I1B"},{"command":"I2B"},{"command":"I3B"},{"command":"I4B"},{"command":"I5B"},{"command":"I6B"},{"command":"J0B"},{"command":"J1B"},{"command":"J2B"},{"command":"J3B"},{"command":"J4B"},{"command":"J5B"},{"command":"J6B"},{"command":"K0B"},{"command":"K1B"},{"command":"K2B"},{"command":"K3B"},{"command":"K4B"},{"command":"K5B"},{"command":"K6B"},{"command":"L0B"},{"command":"L1B"},{"command":"L2B"},{"command":"L3B"},{"command":"L4B"},{"command":"L5B"},{"command":"L6B"},{"command":"M0C"},{"command":"M1C"},{"command":"M2C"},{"command":"M3C"},{"command":"M4C"},{"command":"M5C"},{"command":"M6C"},{"command":"N0C"},{"command":"N1C"},{"command":"N2C"},{"command":"N3C"},{"command":"N4C"},{"command":"N5C"},{"command":"N6C"}],"week_planning4":[{"command":"00C"},{"command":"01C"},{"command":"02C"},{"command":"03C"},{"command":"04C"},{"command":"05C"},{"command":"06C"},{"command":"10C"},{"command":"11C"},{"command":"12C"},{"command":"13C"},{"command":"14C"},{"command":"15C"},{"command":"16C"},{"command":"20C"},{"command":"21C"},{"command":"22C"},{"command":"23C"},{"command":"24C"},{"command":"25C"},{"command":"26C"},{"command":"30C"},{"command":"31C"},{"command":"32C"},{"command":"33C"},{"command":"34C"},{"command":"35C"},{"command":"36C"},{"command":"40C"},{"command":"41C"},{"command":"42C"},{"command":"43C"},{"command":"44C"},{"command":"45C"},{"command":"46C"},{"command":"50C"},{"command":"51C"},{"command":"52C"},{"command":"53C"},{"command":"54C"},{"command":"55C"},{"command":"56C"},{"command":"60C"},{"command":"61C"},{"command":"62C"},{"command":"63C"},{"command":"64C"},{"command":"65C"},{"command":"66C"},{"command":"70B"},{"command":"71B"},{"command":"72B"},{"command":"73B"},{"command":"74B"},{"command":"75C"},{"command":"76C"},{"command":"80B"},{"command":"81B"},{"command":"82B"},{"command":"83B"},{"command":"84B"},{"command":"85B"},{"command":"86B"},{"command":"90C"},{"command":"91C"},{"command":"92C"},{"command":"93C"},{"command":"94C"},{"command":"95B"},{"command":"96B"},{"command":"A0C"},{"command":"A1C"},{"command":"A2C"},{"command":"A3C"},{"command":"A4C"},{"command":"A5B"},{"command":"A6B"},{"command":"B0C"},{"command":"B1C"},{"command":"B2C"},{"command":"B3C"},{"command":"B4C"},{"command":"B5B"},{"command":"B6B"},{"command":"C0B"},{"command":"C1B"},{"command":"C2B"},{"command":"C3B"},{"command":"C4B"},{"command":"C5B"},{"command":"C6B"},{"command":"D0B"},{"command":"D1B"},{"command":"D2B"},{"command":"D3B"},{"command":"D4B"},{"command":"D5B"},{"command":"D6B"},{"command":"E0C"},{"command":"E1C"},{"command":"E2C"},{"command":"E3C"},{"command":"E4C"},{"command":"E5B"},{"command":"E6B"},{"command":"F0C"},{"command":"F1C"},{"command":"F2C"},{"command":"F3C"},{"command":"F4C"},{"command":"F5B"},{"command":"F6B"},{"command":"G0C"},{"command":"G1C"},{"command":"G2C"},{"command":"G3C"},{"command":"G4C"},{"command":"G5B"},{"command":"G6B"},{"command":"H0B"},{"command":"H1B"},{"command":"H2B"},{"command":"H3B"},{"command":"H4B"},{"command":"H5B"},{"command":"H6B"},{"command":"I0B"},{"command":"I1B"},{"command":"I2B"},{"command":"I3B"},{"command":"I4B"},{"command":"I5B"},{"command":"I6B"},{"command":"J0B"},{"command":"J1B"},{"command":"J2B"},{"command":"J3B"},{"command":"J4B"},{"command":"J5B"},{"command":"J6B"},{"command":"K0B"},{"command":"K1B"},{"command":"K2B"},{"command":"K3B"},{"command":"K4B"},{"command":"K5B"},{"command":"K6B"},{"command":"L0B"},{"command":"L1B"},{"command":"L2B"},{"command":"L3B"},{"command":"L4B"},{"command":"L5B"},{"command":"L6B"},{"command":"M0C"},{"command":"M1C"},{"command":"M2C"},{"command":"M3C"},{"command":"M4C"},{"command":"M5B"},{"command":"M6B"},{"command":"N0C"},{"command":"N1C"},{"command":"N2C"},{"command":"N3C"},{"command":"N4C"},{"command":"N5C"},{"command":"N6C"}],"modem":"289C6E000000","reference":"TONE_AQUA_AIR","serial_number":"**************","type":"TONE","name":null,"address":"mon adresse","postalCode":"990000","city":"ma ville","country":"France","usureFiltre":null,"dateLastFilterUpdate":null,"hasFilter":null,"gpsLatitude":0.000000,"gpsLongitude":0.000000,"outdoorAirQualityAvg":null,"isConnected":true,"needUpdate":{"message":"Your app is outdated please update it using the app store and try again","storeAndroid":"https://play.google.com/store","storeApple":"http://appstore.com/aldes"}}]`

**Comment by aalmazanarbs** [comment]
Hi @RiderCrazy,

Thank you for the JSON.

Here we have two problems:

- I don't know all possible values of `reference` field. For a quick fix we can add your value `TONE_AQUA_AIR`.
- The mode is other problema, this integration is waiting the mode is in `indicators.[*].type = 'MODE'` but I can not see in you JSON. In addition, supported modes are [https://github.com/aalmazanarbs/hassio_aldes/blob/master/aldes/product.py#L11)](https://github.com/aalmazanarbs/hassio_aldes/blob/master/aldes/product.py#L11) but it seems that your product has multi mode `current_air_mode` and `current_water_mode`, so I think `POST /aldesoc/v5/users/me/products/{product_id}/commands` will fail too in the way that now works.

I need more information about how your products works since it seems that Aldes API is very inconsistent :(

**Comment by RiderCrazy** [comment]
Hi @aalmazanarbs,

Thanks for your answer and your time.
This product is a 3 in 1, air heater/air conditioner and water heater.
I've got it for 3 months and looking for some integrations for over a year.

I've found people working on it for Jeedom a year ago. But nothing more recent.
Here's the topic : https://community.jeedom.com/t/aldes-connect-api/57068/14
In it, you can find a swagger with a lot of informations but I don't understand everything. Looks like you can update a room temperature but not the mode (there's a boost mode for exemple).
https://community.jeedom.com/uploads/short-url/9rx2gIhfE2YHqTAyR7sRgYnsF5D.txt

Since this file has been almost a year ago, maybe it's outdated too... I don't know

**Comment by aalmazanarbs** [comment]
Hi @RiderCrazy,

Thank you for the information and the OpenAPI.

I have review it but I can not related the APIs with how your product works (take into account that I get InspirAir working checking the Android App and reversing it).

If you can provide the curls to change the three modes of your product and the availables modes, I can add the integration. You can get it by checking the Android App and matching the screens with the OpenAPI. Other option is to sniff the traffic of the Android App when you select the modes with Charles Proxy.

Regards.

**Comment by RiderCrazy** [comment]
Hi @aalmazanarbs,

Sorry to bother you.
Trying to set up a dev environnement (VSC, Docker) and when I try to install the integration, i've got an error which was not on my prod.
`[homeassistant.config_entries] Error occurred loading configuration flow for integration aldes: No module named 'api'`
I'm very new to this (py dev), so I don't know if it's related to your module or my install (HA says that config of this integration can't be done in UI).

**Comment by aalmazanarbs** [comment]
Hi @RiderCrazy,

No problem at all guy!

`api.py` and `product.py` have a cyclic dependency. When running in HA, python module dependency resolves it OK, but in local no, to solve it, just break by using relative dependency `import .api`

**Comment by RiderCrazy** [comment]
It works by replacing with `from . import api`

Edit : I'm going to work on it, at least to get some values. I'll let you know.

**Comment by loregcl** [comment]
hi @aalmazanarbs,

I have the same problem with my installation.

I have an InspiAIR Home S and a Walter sensor, the problem I think is this sensor, right?
How can I add it?
