### ISSUE TITLE
Add EasyHome PureAir Compact CONNECT product

### ISSUE THREAD

**Issue by Fredzxda** [aalmazanarbs/hassio_aldes#11]
Hello,
I can't add this reposituroy to HACS in order to add this integration.
Any idea how to play with ?

**Comment by Fredzxda** [comment]
I copy everything in custom_components and restant HA.
I have the Aldes integration and follow information in issue #10 to have my token and then information about my product: EASY_HOME_CONNECT
Can you tel me where to add this product in your code to verify the compatibility ?

**Comment by Fredzxda** [comment]
Found it :)
I have now one selector.
I ll play with it in the following days and let you know if it work.
I translate it into French too.
How can I contribute to merge the code ?

**Comment by aalmazanarbs** [comment]
> Found it :) I have now one selector. I ll play with it in the following days and let you know if it work. I translate it into French too. How can I contribute to merge the code ?

Of course!! You are welcome!!

**Comment by Fredzxda** [comment]
Thank you @aalmazanarbs.
I do some simple tests right now and work like a charm ;)
So, your job seems to work for my device without rework.
I do a pull request.
Will try to add sensors to have additional informations for next one.

**Comment by aalmazanarbs** [comment]
@Fredzxda Are you to going to add support for HACS in this support or in the next one?

**Comment by Fredzxda** [comment]
In the next one.

Le lun. 29 mai 2023 à 10:58, Alejandro Almazán ***@***.***> a
écrit :
