### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by gbarrena** [aalmazanarbs/hassio_aldes#3]
The integration login fail, look the attach photo,
![aldes](https://user-images.githubusercontent.com/103930158/206240234-498bee90-55b2-4b02-b2d0-2788393b272c.png)

**Comment by aalmazanarbs** [comment]
Hi @gbarrena, thank you for reporting.

The error was related to a change in Aldes API. It has been fixed in the last commit [1e39823](https://github.com/aalmazanarbs/hassio_aldes/commit/1e39823e1c2cd1f6864031f8d2c0a8257ae98558)
