### ISSUE TITLE
Aldes Connect

### ISSUE THREAD

**Issue by loispostula** [aalmazanarbs/hassio_aldes#4]
Does the installation needs to be connected to the AldesConnect modem in order to enable this integration?

**Comment by RiderCrazy** [comment]
Yes.
The integration uses data from aldes cloud application which is updated through the modem.

**Comment by loispostula** [comment]
Thanks a lot, looking forward to use the integration

**Comment by aalmazanarbs** [comment]
Hi @loispostula, yes, you need to have it connected to your InspirAIR device. This integration connects to Aldes Cloud and Aldes Cloud connect AldesConnect Box.

Please note that before using this integration you have to pair your InspirAIR device using AldesConnect App.
