### ISSUE TITLE
 list index out of range #2

### ISSUE THREAD

**Issue by loregcl** [aalmazanarbs/hassio_aldes#7]
hi @aalmazanarbs,

I have the same problem with my installation.

I have an InspiAIR Home S and a Walter sensor, the problem I think is this sensor, right?
How can I add it?

_Originally posted by @loregcl in https://github.com/aalmazanarbs/hassio_aldes/issues/1#issuecomment-1448405636_

**Comment by aalmazanarbs** [comment]
Hi @loregcl, yes, I think it is the problem. As I said in the issue of your comment I do not have access to water sensor and Aldes API is not documented so try and try again with the device is the only the way to develop this integration.

If you can provide the output for the curls for `/aldesoc/v5/users/me/products` and tell actions for the device I can try to add it or even ignoring products other than InspiAIR Home S.

On the other hand I don't now if [https://github.com/RiderCrazy](RiderCrazy) got it working since this project has not received has not received any PR.

**Comment by RiderCrazy** [comment]
Hello @aalmazanarbs 

Well, I've made some changes in order to catch temperature for the sensors of my AquaAir.
Read only, no actions. My code is very dirty so didn't made any PR, and pretty sure I broke yours ^^
Their system is unstable so I did not rely on this sensors anymore.

**Comment by loregcl** [comment]
I have the following output (I modified some personal info):

`[{
        "address": "xxxxxxxxxxx",
        "city": "xxxxxxxxxx",
        "country": "italia",
        "dateLastFilterUpdate": "2021-03-11 11:44:14Z",
        "gpsLatitude": aaaaaaaaaaaaa,
        "gpsLongitude": aaaaaaaaaaaa,
        "hasFilter": true,
        "indicator": {
            "AIR_CO2_CAPT": null,
            "AIR_CO2_VMC": {
                "actualValue": null,
                "previousValue": null
            },
            "AIR_COV1_CAPT": null,
            "AIR_COV2_CAPT": null,
            "AIR_CURRENT_MODE": "V",
            "AIR_CVE_CSN": 0,
            "AIR_DEP_IND": 10,
            "AIR_DTB_IND": 0,
            "AIR_ECHANGE_PWR": 0,
            "AIR_END_MODE": null,
            "AIR_EXCH_ENG": null,
            "AIR_EXTF_FLW": 120,
            "AIR_EXTF_SPD": 2725,
            "AIR_EXTF_TSN": null,
            "AIR_EXT_TPT": 12.5,
            "AIR_FFE_FLW": 120,
            "AIR_FF_CPT": 100,
            "AIR_HYGR_CAPT": null,
            "AIR_OUTSIDE_TPT": 8.0,
            "AIR_PM10_CAPT": null,
            "AIR_PM2_5_CAPT": null,
            "AIR_REJECT_TPT": 8.5,
            "AIR_SET_SPD": 1,
            "AIR_START_MODE": null,
            "AIR_TEMP_CAPT": null,
            "AIR_TII_EST": null,
            "AIR_TTE_CSN": 0,
            "AIR_VI_CSN": 0,
            "AIR_VI_SPD": 2757,
            "AIR_VV_TSN": null,
            "Co2": {
                "currentValue": 0.0,
                "l1": [400.0, 800.0],
                "l2": [800.0, 1200.0],
                "l3": [1200.0, 1400.0],
                "max": [1400.0, 2000.0]
            },
            "CurrentModeOverride": false,
            "H2O_EMBEDDED": {
                "actualValue": null,
                "previousValue": null
            },
            "H2O_VMC": {
                "actualValue": null,
                "previousValue": null
            },
            "H2o": {
                "currentValue": null,
                "l1": null,
                "l2": null,
                "l3": null,
                "max": null
            },
            "Qai": {
                "actualValue": null,
                "polluantDominant": null,
                "previousValue": null
            },
            "QaiIndex": {
                "currentValue": null,
                "l1": [0.0, 25.0],
                "l2": [25.0, 50.0],
                "l3": [50.0, 75.0],
                "max": [75.0, 100.0]
            },
            "SENSOR0_10_1": {
                "actualValue": null,
                "previousValue": null
            },
            "SENSOR0_10_1_NAME": null,
            "SENSOR0_10_2": {
                "actualValue": null,
                "previousValue": null
            },
            "SENSOR0_10_2_NAME": null,
            "Sensor0101MinMax": [null, null],
            "Sensor0102MinMax": [null, null],
            "indicatorType": "AIR_Indicator"
        },
        "indicators": [{
                "date": "2023-02-28T12:13:01.791Z",
                "type": "MODE",
                "value": "V"
            }, {
                "date": "2023-02-28T12:13:01.791Z",
                "type": "QAI_INDEX",
                "value": null
            }, {
                "date": "2023-03-01T12:11:31.988Z",
                "type": "CLOUD_CONTROLLED",
                "value": null
            }, {
                "date": "2023-03-01T12:11:32.009Z",
                "type": "SELF_CONTROLLED",
                "value": false
            }
        ],
        "isConnected": true,
        "lastUpdatedDate": "2023-03-01 10:08:16Z",
        "masters": ["98D863E79A0A"],
        "modem": "98D863FF1036",
        "name": "",
        "needUpdate": {
            "message": "Your app is outdated please update it using the app store and try again",
            "storeAndroid": "https://play.google.com/store",
            "storeApple": "http://appstore.com/aldes"
        },
        "outdoorAirQualityAvg": 47.675333212662956,
        "postalCode": "xxxxx",
        "reference": "INSPIRAIR_HOME_S",
        "serial_number": "N/A",
        "slaves": ["98D863E79A0A"],
        "thermostats": null,
        "type": "AIR",
        "usureFiltre": 0,
        "week_planning": [{
                "command": "00V"
            }, {
                "command": "01V"
            }, {
                "command": "02V"
            }, {
                "command": "03V"
            }, {
                "command": "04V"
            }, {
                "command": "05V"
            }, {
                "command": "06V"
            }, {
                "command": "10V"
            }, {
                "command": "11V"
            }, {
                "command": "12V"
            }, {
                "command": "13V"
            }, {
                "command": "14V"
            }, {
                "command": "15V"
            }, {
                "command": "16V"
            }, {
                "command": "20V"
            }, {
                "command": "21V"
            }, {
                "command": "22V"
            }, {
                "command": "23V"
            }, {
                "command": "24V"
            }, {
                "command": "25V"
            }, {
                "command": "26V"
            }, {
                "command": "30V"
            }, {
                "command": "31V"
            }, {
                "command": "32V"
            }, {
                "command": "33V"
            }, {
                "command": "34V"
            }, {
                "command": "35V"
            }, {
                "command": "36V"
            }, {
                "command": "40V"
            }, {
                "command": "41V"
            }, {
                "command": "42V"
            }, {
                "command": "43V"
            }, {
                "command": "44V"
            }, {
                "command": "45V"
            }, {
                "command": "46V"
            }, {
                "command": "50V"
            }, {
                "command": "51V"
            }, {
                "command": "52V"
            }, {
                "command": "53V"
            }, {
                "command": "54V"
            }, {
                "command": "55V"
            }, {
                "command": "56V"
            }, {
                "command": "60V"
            }, {
                "command": "61V"
            }, {
                "command": "62V"
            }, {
                "command": "63V"
            }, {
                "command": "64V"
            }, {
                "command": "65V"
            }, {
                "command": "66V"
            }, {
                "command": "70V"
            }, {
                "command": "71V"
            }, {
                "command": "72V"
            }, {
                "command": "73V"
            }, {
                "command": "74V"
            }, {
                "command": "75V"
            }, {
                "command": "76V"
            }, {
                "command": "80V"
            }, {
                "command": "81V"
            }, {
                "command": "82V"
            }, {
                "command": "83V"
            }, {
                "command": "84V"
            }, {
                "command": "85V"
            }, {
                "command": "86V"
            }, {
                "command": "90V"
            }, {
                "command": "91V"
            }, {
                "command": "92V"
            }, {
                "command": "93V"
            }, {
                "command": "94V"
            }, {
                "command": "95V"
            }, {
                "command": "96V"
            }, {
                "command": "A0Z"
            }, {
                "command": "A1V"
            }, {
                "command": "A2V"
            }, {
                "command": "A3V"
            }, {
                "command": "A4V"
            }, {
                "command": "A5V"
            }, {
                "command": "A6V"
            }, {
                "command": "B0Z"
            }, {
                "command": "B1Z"
            }, {
                "command": "B2Z"
            }, {
                "command": "B3Z"
            }, {
                "command": "B4Z"
            }, {
                "command": "B5V"
            }, {
                "command": "B6V"
            }, {
                "command": "C0Z"
            }, {
                "command": "C1Z"
            }, {
                "command": "C2Z"
            }, {
                "command": "C3Z"
            }, {
                "command": "C4Z"
            }, {
                "command": "C5V"
            }, {
                "command": "C6V"
            }, {
                "command": "D0Z"
            }, {
                "command": "D1Z"
            }, {
                "command": "D2Z"
            }, {
                "command": "D3Z"
            }, {
                "command": "D4Z"
            }, {
                "command": "D5V"
            }, {
                "command": "D6V"
            }, {
                "command": "E0Z"
            }, {
                "command": "E1Z"
            }, {
                "command": "E2Z"
            }, {
                "command": "E3Z"
            }, {
                "command": "E4Z"
            }, {
                "command": "E5V"
            }, {
                "command": "E6V"
            }, {
                "command": "F0Z"
            }, {
                "command": "F1Z"
            }, {
                "command": "F2Z"
            }, {
                "command": "F3Z"
            }, {
                "command": "F4Z"
            }, {
                "command": "F5V"
            }, {
                "command": "F6V"
            }, {
                "command": "G0Z"
            }, {
                "command": "G1Z"
            }, {
                "command": "G2Z"
            }, {
                "command": "G3Z"
            }, {
                "command": "G4Z"
            }, {
                "command": "G5V"
            }, {
                "command": "G6V"
            }, {
                "command": "H0V"
            }, {
                "command": "H1V"
            }, {
                "command": "H2V"
            }, {
                "command": "H3V"
            }, {
                "command": "H4V"
            }, {
                "command": "H5V"
            }, {
                "command": "H6V"
            }, {
                "command": "I0V"
            }, {
                "command": "I1V"
            }, {
                "command": "I2V"
            }, {
                "command": "I3V"
            }, {
                "command": "I4V"
            }, {
                "command": "I5V"
            }, {
                "command": "I6V"
            }, {
                "command": "J0V"
            }, {
                "command": "J1V"
            }, {
                "command": "J2V"
            }, {
                "command": "J3V"
            }, {
                "command": "J4V"
            }, {
                "command": "J5V"
            }, {
                "command": "J6V"
            }, {
                "command": "K0V"
            }, {
                "command": "K1V"
            }, {
                "command": "K2V"
            }, {
                "command": "K3V"
            }, {
                "command": "K4V"
            }, {
                "command": "K5V"
            }, {
                "command": "K6V"
            }, {
                "command": "L0V"
            }, {
                "command": "L1V"
            }, {
                "command": "L2V"
            }, {
                "command": "L3V"
            }, {
                "command": "L4V"
            }, {
                "command": "L5V"
            }, {
                "command": "L6V"
            }, {
                "command": "M0V"
            }, {
                "command": "M1V"
            }, {
                "command": "M2V"
            }, {
                "command": "M3V"
            }, {
                "command": "M4V"
            }, {
                "command": "M5V"
            }, {
                "command": "M6V"
            }, {
                "command": "N0V"
            }, {
                "command": "N1V"
            }, {
                "command": "N2V"
            }, {
                "command": "N3V"
            }, {
                "command": "N4V"
            }, {
                "command": "N5V"
            }, {
                "command": "N6V"
            }
        ],
        "week_planning2": null,
        "week_planning3": null,
        "week_planning4": null
    }, {
        "address": "xxxxxxxx",
        "city": "xxxxxxxx",
        "country": "Italy",
        "dateLastFilterUpdate": null,
        "gpsLatitude": aaaaaaaaaaaa,
        "gpsLongitude": aaaaaaaaaaaa,
        "hasFilter": null,
        "indicator": {
            "co2": {
                "currentValue": 440.0,
                "l1": [400.0, 800.0],
                "l2": [800.0, 1200.0],
                "l3": [1200.0, 1400.0],
                "max": [1400.0, 2000.0]
            },
            "cov": {
                "currentValue": 76.0,
                "l1": [0.0, 151.0],
                "l2": [151.0, 301.0],
                "l3": [301.0, 451.0],
                "max": [451.0, 600.0]
            },
            "h2o": {
                "currentValue": 55.0,
                "l1": [40.0, 60.0],
                "l2": [30.0, 70.0],
                "l3": [25.0, 75.0],
                "max": [0.0, 100.0]
            },
            "indicatorType": "OQAI_Indicator",
            "pm25": {
                "currentValue": 1.0,
                "l1": [0.0, 16.0],
                "l2": [16.0, 31.0],
                "l3": [31.0, 51.0],
                "max": [51.0, 150.0]
            },
            "qaiData": {
                "alertMode": false,
                "error": "0",
                "id": null,
                "serialNumber": "1233612336123361233612336",
                "settings": {
                    "alertMode": false,
                    "automaticFromDate": "2021-03-01 16:30:56Z",
                    "automaticTime": 0,
                    "automaticToDate": "2021-03-01 16:30:56Z",
                    "cloudFrequency": 30,
                    "displayType": 2,
                    "favoriteDisplay": 1,
                    "isAutomaticEnable": true,
                    "language": "it",
                    "luminosity": 1,
                    "qaiData": 4038
                },
                "swVersion": "Ver 1.0.4",
                "temperature": 17.4
            },
            "qaiIndex": {
                "currentValue": 12.0,
                "l1": [0.0, 25.0],
                "l2": [25.0, 50.0],
                "l3": [50.0, 75.0],
                "max": [75.0, 100.0]
            }
        },
        "indicators": [{
                "date": "2023-02-28T12:12:04.124Z",
                "type": "QAI_INDEX",
                "value": 12
            }, {
                "date": "2023-03-01T12:11:33.856Z",
                "type": "CLOUD_CONTROLLED",
                "value": null
            }, {
                "date": "2023-03-01T12:11:33.867Z",
                "type": "SELF_CONTROLLED",
                "value": false
            }
        ],
        "isConnected": true,
        "lastUpdatedDate": null,
        "masters": ["98D863FF1036"],
        "modem": "98D863E79A0A",
        "name": null,
        "needUpdate": {
            "message": "Your app is outdated please update it using the app store and try again",
            "storeAndroid": "https://play.google.com/store",
            "storeApple": "http://appstore.com/aldes"
        },
        "outdoorAirQualityAvg": null,
        "postalCode": "62012",
        "reference": "OQAI",
        "serial_number": "N/A",
        "slaves": ["98D863FF1036"],
        "thermostats": null,
        "type": "OQAI",
        "usureFiltre": 0,
        "week_planning": [],
        "week_planning2": null,
        "week_planning3": null,
        "week_planning4": null
    }
]`

I hope it can be useful.

thanks

**Comment by aalmazanarbs** [comment]
Hi @loregcl,

As I said previously, the API of Aldes is not documented and I can not reverse products I don't know or even I don't understand its purpose (for example, OQAI is an air quality meter but I don't know if something can be changed in this product or what information is relevant to show).

So I have decided filter the products that this integration support, so at least, known products will work. Please check new code.

For new products I need requests to modify the product and what data is relevant to show in home assistant.

**Comment by loregcl** [comment]
Thank you!
now the integration works with my Inspiair Home S.
I hope you can receive more data from other users in order to add also the air quality meter (Walter).

On my side I can provide the Aldes app screenshot to see the info they public on it.

![1](https://user-images.githubusercontent.com/77339969/224680728-d4c0a4da-5283-4cc2-8c6a-4e40300dfc16.jpg)
![2](https://user-images.githubusercontent.com/77339969/224680756-5e7ca390-fad1-45bf-bd5e-1298bc044fdb.jpg)
![3](https://user-images.githubusercontent.com/77339969/224680775-634a0276-f963-4f2f-8fc1-80e7ef4834dc.jpg)
![4](https://user-images.githubusercontent.com/77339969/224680792-b83a0f95-4165-4a8b-bb96-4b51fc03b825.jpg)
![5](https://user-images.githubusercontent.com/77339969/224680810-5ba48288-78f2-4de8-ad1b-2d7a0df87ac1.jpg)
