### ISSUE TITLE
hass.config_entries.async_setup_platforms replaced

### ISSUE THREAD

**Issue by RiderCrazy** [aalmazanarbs/hassio_aldes#8]
Hi @aalmazanarbs 

FYI
https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/

__init__.py line 35

**Comment by aalmazanarbs** [comment]
Hi @RiderCrazy, thank you for the new. It was fixed https://github.com/aalmazanarbs/hassio_aldes/commit/1978c58ef27949fc204a407907cbb149b0ec99c3
